spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MindBridge
    username: root  # MySQL 사용자명
    password: mingyun2417!  # MySQL 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # (옵션: create, update, validate, none)
      open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true  # SQL 실행 로그 출력
    format-sql: true # SQL 로그를 보기 좋게 포맷팅

  sql:
    init:
      mode: always  # (옵션: always, never)
